### PR TITLE
Fix interrogation link

### LINKED ISSUE #1571: In the dashboard, link on the "?" button in the ethereum repo card is broken
Screenshot_20230828_153259

The "?" button redirects to http://my.dappnode/dashboard/system/repository. Should probably be http://my.dappnode/repository/eth

### PR DESCRIPTION
**Pull request by Marketen**
closes #1571 

To test, open dappmanager and click on "?" button. it should navigate to /repository/eth view, where you can swap local or remote ethereum repo.

Test back button: install /ipfs/QmcqMTkaU7jwmVKRC7WmRX6mRfiH54T38AzyresvBbKBNe. Get to the disclaimer page and click on "back" button. Should redirect to setup.

### CODE REVIEW

File: packages/admin-ui/src/pages/system/data.ts [hunk 1]
```diff
@@ -12,7 +12,7 @@ export const subPaths = {
   identity: "identity",
   security: "security",
   autoUpdates: "auto-updates",
-  repository: "repository",
```
Comment (dsimog01) [inline packages/admin-ui/src/pages/system/data.ts:15]: I would leave this subpath like that

File: packages/admin-ui/src/pages/system/data.ts [hunk 2]
```diff
@@ -26,7 +26,7 @@ export const subPaths = {
 };
 
 // Computed paths
-export const activateFallbackPath = `${pathName}/${subPaths.repository}`;
+export const activateFallbackPath = `${subPaths.repository}`;
```
Comment (dsimog01) [inline packages/admin-ui/src/pages/system/data.ts:29]: And here:
```
export const activateFallbackPath = `${subPaths.repository}/eth`;
```

Comment (Marketen) [reply packages/admin-ui/src/pages/system/data.ts]: fixed
